  os: linux
  dist: focal

  jobs:
    include:
      - language: python
        script:
          - python hello.py

      - language: smalltalk
        before_install:
          - "sudo apt-get install libpulse0"
        group: edge
        arch: arm64-graviton2
        virt: lxd
        smalltalk_vm:
          - Squeak-5.0
        smalltalk:
          - Squeak64-trunk
      - language: smalltalk
        before_install:
          - "sudo apt-get install libpulse0"
        smalltalk_vm:
          - Squeak-5.0
        smalltalk:
          - Squeak64-trunk
