  os: linux
  dist: focal
  arch: arm64-graviton2
  group: dev
  jobs:
    include:
      - language: python
        script:
          - python hello.py

      - language: smalltalk
        smalltalk_vm:
          - Squeak-5.0
        smalltalk:
          - Squeak64-trunk
